eshop_pbp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_fresh_bakes_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, login_user, logout_user, register, edit_fresh_bakes, delete_fresh_bakes, add_bakes_entry_ajax, create_mood_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create_fresh_bakes_entry', create_fresh_bakes_entry, name='create_fresh_bakes_entry'),
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('edit-fresh-bakes/<uuid:id>', edit_fresh_bakes, name='edit_fresh_bakes'),
    path('delete/<uuid:id>', delete_fresh_bakes, name='delete_fresh_bakes'),
    path('create-ajax/', add_bakes_entry_ajax, name='add_bakes_entry_ajax'),
    path('create-flutter/', create_mood_flutter, name='create_mood_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    production_date = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class FreshBakesForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)
    
    def clean_description(self):
        desc = self.cleaned_data["description"]
        return strip_tags(desc)

main/views.py
from main.forms import FreshBakesForm
from main.models import Product
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import datetime
from django.urls import reverse
import json
from django.http import JsonResponse

@csrf_exempt
def create_mood_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_bakes = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"]
        )

        new_bakes.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

def create_fresh_bakes_entry(request):
    form = FreshBakesForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        fresh_bakes = form.save(commit=False)
        fresh_bakes.user = request.user
        fresh_bakes.save()
        return redirect('main:show_main')  

    context = {'form': form}
    return render(request, "create_fresh_bakes_entry.html", context)

def edit_fresh_bakes(request,id):
    fresh_bakes = Product.objects.get(pk=id)
    form = FreshBakesForm(request.POST or None, instance=fresh_bakes)
    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, "edit_fresh_bakes.html", context)

def delete_fresh_bakes(request, id):
    fresh_bakes = Product.objects.get(pk=id)
    fresh_bakes.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def login_user(request):
   if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Yay! We successfully created your account!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@login_required(login_url='/login')
def show_main(request):
    context = {
        'appname' : 'YumYum Bakeshop',
        'name': request.user.username,
        'class': 'PBP D',
        'npm': '2306207972',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

@csrf_exempt
@require_POST
def add_bakes_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    description = strip_tags(request.POST.get("description"))
    price = request.POST.get("price")
    user = request.user
    if name=="" or description=="":
        return HttpResponse(b"ERROR: Invalid data.", status=400)
    new_bakes = Product(
        name=name, description=description,
        price=price,
        user=user
    )
    new_bakes.save()
    return HttpResponse(b"CREATED", status=201)


def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/card_bakes.html
<div class="relative break-inside-avoid">
    <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2">
      <div class="w-[4rem] h-8 bg-rose-400 rounded-md opacity-80 -rotate-45"></div>
    </div>
  
    <!-- Card -->
    <div class="relative top-5 w-120 h-60 bg-orange-100 shadow-lg rounded-lg mb-6 flex flex-col border-2 border-orange-300 transform rotate-1 hover:rotate-0 hover:scale-105 hover:animate-shake transition-transform duration-300 overflow-hidden">
        <div class="bg-rose-200 text-gray-800 p-4 rounded-t-lg border-b-2 border-orange-300">
          <h3 class="font-bold text-xl mb-2">{{ fresh_bakes.name }}</h3>
          <p class="text-gray-600">{{ fresh_bakes.production_date }}</p>
        </div>
      
        <div class="p-4 bg-orange-50 flip-card-back w-full h-full transition-transform duration-700 ease-in-out hover:rotate-y-180">
          <div class="flip-content-front">
            <p class="font-semibold text-lg mb-2">Description</p>
            <p class="text-gray-700 mb-2 truncate whitespace-nowrap">{{ fresh_bakes.description }}</p>
          </div>
          <div class="flip-content-back absolute inset-0 flex items-center justify-center transform rotate-y-180">
            <div>
              <p class="font-semibold text-lg mb-2">Price</p>
              <p class="text-gray-700 font-bold text-2xl">{{ fresh_bakes.price }}</p>
            </div>
          </div>
        </div>
    </div>
      
  
    <!-- Tombol edit dan delete -->
    <div class="absolute top-0 -right-4 flex space-x-1">
      <a href="{% url 'main:edit_fresh_bakes' fresh_bakes.pk %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </a>
      <a href="{% url 'main:delete_fresh_bakes' fresh_bakes.pk %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>

  
  <!-- Animasi -->
  <style>
    @keyframes shake {
      0% { transform: rotate(1deg); }
      25% { transform: rotate(-1deg); }
      50% { transform: rotate(1deg); }
      75% { transform: rotate(-1deg); }
      100% { transform: rotate(1deg); }
    }
    .animate-shake {
      animation: shake 0.5s ease-in-out infinite;
    }
  
    .flip-card-back {
      transform-style: preserve-3d;
      perspective: 1000px;
      position: relative;
    }
    .flip-content-front, .flip-content-back {
      backface-visibility: hidden;
      position: absolute;
      width: 100%;
      height: 100%;
    }
    .flip-content-back {
      transform: rotateY(180deg);
    }
    .hover\:rotate-y-180:hover {
      transform: rotateY(180deg);
    }
  </style>
  

main/templates/card_info.html
<div class="bg-rose-700 rounded-xl overflow-hidden border-2 border-rose-800">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-white">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/create_fresh_bakes_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Mood</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-orange-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-rose-800">Add Fresh Bakes</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-orange-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-orange-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-rose-800 text-white font-semibold px-6 py-3 rounded-lg hover:bg-rose-700 transition duration-300 ease-in-out w-full">
            Add Fresh Bakes
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% include 'navbar.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="min-h-screen flex items-center justify-center w-screen bg-orange-100 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-orange-900">
        Welcome bakers! Login here
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-orange-300 placeholder-orange-500 text-orange-900 rounded-t-md focus:outline-none focus:ring-rose-500 focus:border-rose-500 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-orange-300 placeholder-orange-500 text-orange-900 rounded-b-md focus:outline-none focus:ring-rose-500 focus:border-rose-500 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-rose-600 hover:bg-rose-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-rose-500">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-rose-500 hover:text-rose-300">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>YumYum Bakeshop</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-orange-100 flex flex-col">
  <div class="p-2 mb-6 relative">
    <div class="relative grid grid-cols-1 z-30 md:grid-cols-3 gap-8">
      {% include "card_info.html" with title='NPM' value=npm %}
      {% include "card_info.html" with title='Name' value=name %}
      {% include "card_info.html" with title='Class' value=class %}
    </div>
    <div class="w-full px-6  absolute top-[44px] left-0 z-20 hidden md:flex">
      <div class="w-full min-h-4 bg-rose-700">
      </div>
    </div>
    <div class="h-full w-full py-6  absolute top-0 left-0 z-20 md:hidden flex ">
      <div class="h-full min-w-4 bg-rose-700 mx-auto">
      </div>
    </div>
</div>
    <div class="px-3 mb-4">
      <div class="flex rounded-md items-center bg-rose-600 py-2 px-4 w-fit">
        <h1 class="text-white text-center">Last Login: {{last_login}}</h1>
      </div>
    </div>
    <div class="flex justify-end mb-6">
      <a href="{% url 'main:create_fresh_bakes_entry' %}" class="bg-rose-600 hover:bg-rose-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mx-4">
        <button>Add New Fresh Bakes</button>
      </a>
      <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-rose-700 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
        Add New Fresh Bakes by AJAX
      </button>
    </div>
    <div id="fresh_bakes_entry_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-orange-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-orange-900">
            Add New Fresh Bakes
          </h3>
          <button type="button" class="text-orange-400 bg-transparent hover:bg-orange-200 hover:text-orange-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <div id="formErrors" class="mb-4 text-red-600"></div>
          <form id="FreshBakesForm">
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-orange-700">Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border border-orange-300 rounded-md p-2 hover:border-rose-700" placeholder="Enter your bakes" required>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-orange-700">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-orange-300 rounded-md p-2 hover:border-rose-700" placeholder="Bakes description" required></textarea>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-orange-700">Price</label>
              <input type="number" id="price" name="price" min="1" max="1000000000000000" class="mt-1 block w-full border border-orange-300 rounded-md p-2 hover:border-rose-700" required>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-orange-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-orange-500 hover:bg-orange-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitFreshBakesEntry" form="FreshBakesForm" class="bg-rose-700 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>
</div>
<script>
  function addFreshBakesEntry() {
    fetch("{% url 'main:add_bakes_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#FreshBakesForm')),
    })
    .then(response => {
      if (!response.ok){
        throw new Error('Invalid data');
      }
      return refreshBakesEntries()})
    .then(() =>{
      document.getElementById("FreshBakesForm").reset(); 
      document.getElementById('formErrors').innerHTML = '';
      document.querySelector("[data-modal-toggle='crudModal']").click();
      hideModal();
    })

    .catch(error => {
      document.getElementById('formErrors').innerHTML = `<p>Data invalid. Please try again.</p>`;
    });
    return false;
  }
  async function getBakesEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }
  async function refreshBakesEntries() {
    document.getElementById("fresh_bakes_entry_cards").innerHTML = "";
    document.getElementById("fresh_bakes_entry_cards").className = "";
    const bakeEntries = await getBakesEntries();
    let htmlString = "";
    let classNameString = "";
    if (bakeEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/sad_image.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">You've got no bakes yet.</p>
            </div>
        `;
    }
    else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
        bakeEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description= DOMPurify.sanitize(item.fields.description);
            const price = item.fields.price;
            htmlString += `
            <div class="relative break-inside-avoid">
              <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2">
                <div class="w-[4rem] h-8 bg-rose-400 rounded-md opacity-80 -rotate-45"></div>
              </div>
            
              <!-- Card -->
              <div class="relative top-5 w-120 h-60 bg-orange-100 shadow-lg rounded-lg mb-6 flex flex-col border-2 border-orange-300 transform rotate-1 hover:rotate-0 hover:scale-105 hover:animate-shake transition-transform duration-300 overflow-hidden">
                  <div class="bg-rose-200 text-gray-800 p-4 rounded-t-lg border-b-2 border-orange-300">
                    <h3 class="font-bold text-xl mb-2">${item.fields.name}</h3>
                    <p class="text-gray-600">${item.fields.production_date}</p>
                  </div>
                
                  <div class="p-4 bg-orange-50 flip-card-back w-full h-full transition-transform duration-700 ease-in-out hover:rotate-y-180">
                    <div class="flip-content-front">
                      <p class="font-semibold text-lg mb-2">Description</p>
                      <p class="text-gray-700 mb-2 truncate whitespace-nowrap">${item.fields.description}</p>
                    </div>
                    <div class="flip-content-back absolute inset-0 flex items-center justify-center transform rotate-y-180">
                      <div>
                        <p class="font-semibold text-lg mb-2">Price</p>
                        <p class="text-gray-700 font-bold text-2xl">${item.fields.price}</p>
                      </div>
                    </div>
                  </div>
              </div>
                
              <!-- Tombol edit dan delete -->
              <div class="absolute top-0 -right-4 flex space-x-1">
                <a href="/edit-fresh-bakes/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                  </svg>
                </a>
                <a href="/delete/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
            </div>
            `;
        });
    }
    document.getElementById("fresh_bakes_entry_cards").className = classNameString;
    document.getElementById("fresh_bakes_entry_cards").innerHTML = htmlString;
  }
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');
  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');
      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }
  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');
      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');
      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }
  
  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("submitFreshBakesEntry").onclick = addFreshBakesEntry;
  refreshBakesEntries();
</script>
<style>
  @keyframes shake {
    0% { transform: rotate(1deg); }
    25% { transform: rotate(-1deg); }
    50% { transform: rotate(1deg); }
    75% { transform: rotate(-1deg); }
    100% { transform: rotate(1deg); }
  }
  .animate-shake {
    animation: shake 0.5s ease-in-out infinite;
  }

  .flip-card-back {
    transform-style: preserve-3d;
    perspective: 1000px;
    position: relative;
  }
  .flip-content-front, .flip-content-back {
    backface-visibility: hidden;
    position: absolute;
    width: 100%;
    height: 100%;
  }
  .flip-content-back {
    transform: rotateY(180deg);
  }
  .hover\:rotate-y-180:hover {
    transform: rotateY(180deg);
  }
</style>
{% endblock content %}